### ISSUE TITLE
Add Details of the Benchmarking Computer to README.md

### ISSUE THREAD

**Issue by matthewcrews** [jinyus/related_post_gen#118]
It would be good to know what hardware these benchmarks are being measured on.

**Comment by jinyus** [comment]
On github workflow free tier:

-   CPU: 2 vCPUs
-   RAM: 7GB
-   OS: Ubuntu 22.04

[Source](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
