### ISSUE TITLE
Clarification for the use of SIMD/Assembly

### ISSUE THREAD

**Issue by matthewcrews** [jinyus/related_post_gen#126]
# Context
- The README.md originally said that assembly cannot be inlined.
- .NET can detect the presence of hardware acceleration of 128 and 256-bit registers
- .NET enables the use of assembly without having to inline assembly

# Question
Would a solution using SIMD registers be allowed if it does not inline assembly?

**Comment by jinyus** [comment]
I'm inclined to say no as that still involves calling foreign code.

**Comment by jinyus** [comment]
Still not convinced, I would like to see how it's done.

**Comment by matthewcrews** [comment]
Looks like this:
![image](https://github.com/jinyus/related_post_gen/assets/1593215/3f28c297-445f-482b-ab51-40b27202406d)

**Comment by jinyus** [comment]
Looks okay, submit the PR when you're ready

**Comment by matthewcrews** [comment]
It's certainly more complex but if this isn't acceptable I suggest adding a stipulation for no taking advantage of specific hardware.

I'm still putting it together but I was just curious "how far" we're allowed to push things 😊.

**Comment by matthewcrews** [comment]
It actually ends up being slower, which I kind of suspected.

**Comment by jinyus** [comment]
Well it was worth a try

**Comment by matthewcrews** [comment]
Here's what it looks like in case you are interested:
https://github.com/matthewcrews/related_post_gen/blob/fsharp-alt-sort/fsharp/Program.fs
