### ISSUE TITLE
Difference in the number of runs

### ISSUE THREAD

**Issue by algunion** [jinyus/related_post_gen#134]
I noticed that some languages have the statistics calculated based on ten runs while others are only evaluated five times.

I suggest using the same number of runs for all the languages: in that way, an outlier (on either side) will have the chance to impact the mean by the same weight. Right now - an outlier in the 5-runs languages will have a greater weight.

**Comment by jinyus** [comment]
reopen until done.

**Comment by jinyus** [comment]
done [https://github.com/jinyus/related_post_gen/commit/cccf06b955907e9bbae9b531a2d4a6bc8eefd09d](https://github.com/jinyus/related_post_gen/commit/cccf06b955907e9bbae9b531a2d4a6bc8eefd09d)
