### ISSUE TITLE
[Rules] Specific hardware targeting (rust)

### ISSUE THREAD

**Issue by tdelmas** [jinyus/related_post_gen#142]
Does that rule "No: Specific hardware targeting" means the code should not be written to target a specific hardware, or does that also includes compilations options such as the rust:

File `.cargo/config.toml`

```toml
[build]
rustflags = ["-C", "target-cpu=native"]
```
From https://nnethercote.github.io/perf-book/build-configuration.html#cpu-specific-instructions

Which doesn't target a specific hardware, but compile for the hardware it runs on. Which is different:
- The *code* works for any hardware
- Only the *compiled binary* will be restricted to the hardware it was compiled on (but without it, in Rust, the binary is still restricted to the CPU architecture class)

With that configuration, I observe ~25% speedup (on GitHub codespace) for `rust` (but it's slower with `rust_con`)

**Comment by jinyus** [comment]
The rule was originally made to prevent simd optimization on certain CPUs, so this would fall into that category.

**Comment by tdelmas** [comment]
Thank you for the clarification
