### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mnj** [jinyus/related_post_gen#145]
I think you could improve it, by having multiple solutions per language similar to how this was done for benchmarking primes in all the different languages:
https://github.com/PlummersSoftwareLLC/Primes

Also seems a bit better to use a docker container so it's easier to reproduce locally, using the shared Github runner is unreliable at best times, depending on what else is going on at that moment.

**Comment by jinyus** [comment]
This has grown bigger than I originally intended but I'm love the idea. I can't commit the time to it though. 

To make the change easier, I could just  put a Dockerfile in each subdir and a script to build and run everything.

**Comment by mnj** [comment]
The main problem is it's hard to replicate the results/runs, when it's not dockerized when all the less commonly used languages are added, I had to remove nim*, because it didn't play well with a self-hosted dedicated runner on Ubuntu 22.04, and the other problem is the shared nature of the standard GitHub shared runner, it's not optimal for benchmarks since it's shared by others.

This is what a dedicated runner (Azure F32s - 32 Core, 64GB mem vm) gives in comparison, much more consistent results:
https://github.com/mnj/related_post_gen/actions/runs/6433667036
https://github.com/mnj/related_post_gen/pull/2/files

*) It just kept throwing "curl: (23) Failure writing output to destination"

**Comment by jinyus** [comment]
Dockerfile created to run all tests.
