### ISSUE TITLE
Bounds checking a requirement?

### ISSUE THREAD

**Issue by matthewcrews** [jinyus/related_post_gen#159]
I noticed that the solution for Julia uses a data structure that does not have bounds checks (StrideArray)[https://github.com/JuliaSIMD/StrideArraysCore.jl]. Is this now allowed? If so, I can drop down to managed pointers (included in .NET) in F# and speed it up by removing bounds checks.

**Comment by jinyus** [comment]
The contributor was supposed to submit a pr to remedy that [https://github.com/jinyus/related_post_gen/pull/146#issuecomment-1751665006](https://github.com/jinyus/related_post_gen/pull/146#issuecomment-1751665006)

It just slipped by mind. I will revert the pr that introduced it.
