### ISSUE TITLE
Rules clarification

### ISSUE THREAD

**Issue by radekm** [jinyus/related_post_gen#169]
Hi,

I have two questions about the rules. ReadMe forbids following:

- Unsafe code blocks
- Disabling runtime checks (bounds etc)

But for example Rust solution uses `smallstr` crate which contains unsafe code.
Or even Rust's standard library uses unsafe and disables runtime checks.
The situation for .NET is similar - standard library uses unsafe.

Another example is Zig which is compiled with `ReleaseFast` which according
to the [documentation](https://ziglang.org/documentation/0.11.0/#ReleaseFast) disables runtime checks
instead of `ReleaseSafe` which enables them.

1) Is it ok to use a library which uses unsafe code / assembly / disables runtime checks?
2) What about compiler settings? Is okay to disable runtime checks with compiler flags?

**Comment by jinyus** [comment]
Those issues will have to be remedied. Compiler flags that disable runtime checks are not allowed, nor is using libraries that has unsafe code. Unsafe code in the stdlib is fine as there isn't much that can be done about that.

**Comment by jinyus** [comment]
Thanks for reporting. issues has been addressed: ffbec3232d917f6bde5398880469f9fce567a2b9
