### ISSUE TITLE
Suggestion: add Julia to the repo description

### ISSUE THREAD

**Issue by algunion** [jinyus/related_post_gen#188]
I am clearly a Julia user and supporter - so this is expected to come from me.

Just saying that I would like to (also) see Julia in the description:
> Data Processing benchmark featuring Rust, Go, Swift, Zig etc.

This is (obviously) up to you and I also have no idea what are your criteria for including/excluding specific languages from that list.

**Comment by jinyus** [comment]
Since julia is leading, I think this is a fair ask.
