### ISSUE TITLE
Do type assertions and any kind of compute except warmup during the measurement phase

### ISSUE THREAD

**Issue by DrBlury** [jinyus/related_post_gen#205]
It seems like I kicked of a conversation about whether the first call to the related func can stay outside of the measured time or not. 

Original conversation was here:
https://github.com/jinyus/related_post_gen/pull/204

**Comment by algunion** [comment]
> It seems like I kicked of a conversation about whether the first call to the related func can stay outside of the measured time or not.
> 
> Original conversation was here: #204

This opinion should be informed about Julia's facts. _Not understanding_ enough can never be a good reason to demand that Julia include the compile time in the benchmark.

That first call in Julia is basically including the compilation:

![checkthis](https://github.com/jinyus/related_post_gen/assets/3482227/6a81bee6-0e02-488c-8d6a-c28c04c64688)

You can read about that [here ](https://docs.julialang.org/en/v1/manual/performance-tips/#Measure-performance-with-[@time](@ref)-and-pay-attention-to-memory-allocation) - it is public knowledge.

That is why we have things like [`PrecompileTools.jl`](https://docs.julialang.org/en/v1/manual/performance-tips/#Measure-performance-with-[@time](@ref)-and-pay-attention-to-memory-allocation) which are actually making `calls` to compile certain code.

We can make the change and use a precompiled version - but the reason for that should not be rooted in complaints like this.

**Comment by DrBlury** [comment]
Yes it was a misunderstanding and I'm grateful for the explanation. Thank you!
I now know why it's done and that it does not matter as no data is cached and the posts data is just used so each code path gets compiled before the measurement. Thank you for the clarification and I apologize for my mistake and skepticism.

**Comment by algunion** [comment]
> Yes it was a misunderstanding and I'm grateful for the explanation. Thank you! I now know why it's done and that it does not matter as no data is cached and the posts data is just used so each code path gets compiled before the measurement. Thank you for the clarification and I apologize for my mistake and skepticism.

I appreciate your stance on this.

Precompilation/binaries is still somehow a pain in the __ in Julia ecosystem - but we are getting there. We'll try to deliver a precompiled version anyway - it just takes more work to ensure all the branches are touched and no additional compilation takes place when the first function call is made.
