### ISSUE TITLE
Optimizations techniques description

### ISSUE THREAD

**Issue by cyrusmsk** [jinyus/related_post_gen#208]
I am seeing this project not as a race of the languages, but as a good educational project. Where the user of lang X could see some interesting techniques and assumptions from other users and other languages.

That's why I propose to make a table and small document with description of the applied optimizations, so users don't have to monitor and check all other PRs and implementations, but have a single place with all applied things.

It will be even more useful if the author of optimizations will provide small description and main idea of them.

Like what I already saw:
* using pointers instead of strings in Go
* using List for initializing a HashMap and after that initialization of the HashMap based on the array (probably this will prevent many allocation while appending post indexes in the HashMap)
* Several languages trying to use Flat List for Top5 calculations
* etc...

After such optimizations will be prepared it will be possible to create a table: optimizations in columns and languages in rows to see which languages used which optimizations.

**Comment by jinyus** [comment]
I like the idea but that's a mountain of work. I did something similar with the old charts (scroll to the end of readme) that gave a small description of the optimization for each language. That'd be a nice place to start but I cannot commit my time to that.
