### ISSUE TITLE
What's the assumed CPU baseline?

### ISSUE THREAD

**Issue by MichalStrehovsky** [jinyus/related_post_gen#257]
Most languages/compilers have sane defaults (i.e. targeting x64 means one can run the binary on any x64 machine).

Others like to live dangerously and assume something higher. For example Java/GraalVM builds for x86-64-v3 by default and the executable will fail to start on any CPU that doesn't have AVX2. `-march=compatibility` needs to be passed to the compiler to target the sane baseline.

Can we set compilers to assume AVX2/BMI1/BMI2/etc.?

**Comment by jinyus** [comment]
I'm not knowledgeable enough to make a sound decision but I'll say it's safe to assume that it's running on a modern CPU.

**Comment by MichalStrehovsky** [comment]
I saw arch=native was previously [rejected](https://github.com/jinyus/related_post_gen/issues/142#issuecomment-1750542087) and Graal's default is pretty much same as arch=native for Azure F4s v2. I'm not aware of any other compiler setting the default to anything but the lowest possible baseline for the given OS/arch combination (e.g. one can assume SSSE3 on Mac because the first x64 Mac CPUs had SSSE3).

Allowing AVX2 allows exactly the kind of autovectorization that your argument in https://github.com/jinyus/related_post_gen/issues/142#issuecomment-1750542087 was trying to prevent so the consistent choice would be to add `<buildArg>-march=compatibility</buildArg>` to here https://github.com/jinyus/related_post_gen/blob/3a270a9140491f3311ca062820c2d5184485f057/java/pom.xml#L238 and close this issue with that.

**Comment by inv2004** [comment]
Maybe "-march=x86_64-v3" would be ok?

**Comment by MichalStrehovsky** [comment]
> Maybe "-march=x86_64-v3" would be ok?

You mean for graal? That's the default as of this year (so no point specifying that): https://docs.oracle.com/en/graalvm/jdk/20/docs/release-notes/

**Comment by inv2004** [comment]
I about other languages too

**Comment by cyrusmsk** [comment]
> I about other languages too
> […](#)

I think it is easier to fix 1 Graal, than fixing everyone else

**Comment by inv2004** [comment]
I think it is not a question about fixing, but the question about author's
rules

**Comment by cyrusmsk** [comment]
If I correctly understood topic starter - he is pointing out that current settings of Graal is violating already existing rules..

**Comment by inv2004** [comment]
I mixed discussion of the graal with other platforms too - sorry
