### ISSUE TITLE
.NET potential improvement

### ISSUE THREAD

**Issue by cyrusmsk** [jinyus/related_post_gen#262]
Did you try @MichalStrehovsky, @delneg to use TLS for count array in concurrent versions of C# and F#?
https://github.com/dotnet/runtime/pull/82973

**Comment by delneg** [comment]
I personally didn't touch concurrent version

**Comment by Imperatorn** [comment]
Maybe I'll do one for C# if I get the time

**Comment by cyrusmsk** [comment]
TLS was used in one of the last PRs
