### ISSUE TITLE
Input and output files are not containing any multibyte characters

### ISSUE THREAD

**Issue by denkab** [jinyus/related_post_gen#265]
I would like to recommend taking into consideration, if the benchmark is intended as a real-world representation, to mix in non-ASCII characters.

**Comment by jinyus** [comment]
Thanks for the suggestion but that shipped has sailed. I can't modify the problem statement this late into the competition.

**Comment by denkab** [comment]
Clarification, does anything in the rules prevent implementers from choosing libraries that only work with ASCII files and strings? This can make things faster and reduce memory footprint.

**Comment by jinyus** [comment]
That's a tricky one, while the problem doesn't specify, as you said...in a real world scenario, it's reasonable to expect that utf8 is supported. I think I will modify the rules as opposed to modifying the problem.

**Comment by denkab** [comment]
Agreed. And explicit introduction of Unicode support would imply correct and complete implementation including collation, e.g. whether ñ is greater than n and less than o :)

That is indeed a can of worms.
