### ISSUE TITLE
Can zig use ReleaseFast to build the target ?

### ISSUE THREAD

**Issue by kaiwu** [jinyus/related_post_gen#272]
Turns out it out-performs C++ with `ReleaseFast` 
With current `ReleaseSafe` approach, it safe guards everything in *runtime*, which adds significant overhead.
If we squat low enough and examine  the top scorers, none of them is doing this.

**Comment by jinyus** [comment]
Turning off safety is against the rules. If other solutions are doing this, please point them out...as avoiding safety checks that others are doing is not fair.

https://ziglang.org/documentation/master/#toc-ReleaseFast

**Comment by kaiwu** [comment]
none of them are doing it in *runtime* I believe. For example, rust and cpp are checking them only in compile time.
exactly this is not fair for zig

**Comment by jinyus** [comment]
IIUC rust does bounds checks at runtime too: https://nnethercote.github.io/perf-book/bounds-checks.html

and cpp is using `.at` so it also does at runtime. 

Go and d also do runtime checks so allowing zig to remove them isn't fair.

**Comment by cyrusmsk** [comment]
> Rust does not make overflow checks in release, but Nim does.

Can you show docs about that? I’ve tried to find myself, but it wasn’t clearly written.

**Comment by inv2004** [comment]
https://doc.rust-lang.org/cargo/reference/profiles.html#release

**Comment by cyrusmsk** [comment]
> https://doc.rust-lang.org/cargo/reference/profiles.html#release

But it seems (https://rust-lang.github.io/packed_simd/perf-guide/bound_checks.html) that only specifically marked part of the language (unsafe, *_unchecked) is not checked for boundaries in case "debug-assertion=false". The rest of the code in general still checked, in case compiler itself couldn't "prove" that this part could be skipped for checking.

**Comment by inv2004** [comment]
@cyrusmsk 
I am about overflows check, you are about bounds check

**Comment by cyrusmsk** [comment]
> @cyrusmsk
> I am about overflows check, you are about bounds check

Oh. Maybe then add flags from this forum topic? https://github.com/nim-lang/Nim/issues/14504

**Comment by inv2004** [comment]
I think that overflow is dangerous - better to enable it for rust. On the same way - what to do with c/c++?
