### ISSUE TITLE
[Nim] nimble flags

### ISSUE THREAD

**Issue by michaelsbradleyjr** [jinyus/related_post_gen#300]
Compare `main`
https://github.com/jinyus/related_post_gen/blob/37b0d1b667b5119c8a5f2af12d71adab8fae60e5/run.sh#L496
With what I had in #291
https://github.com/jinyus/related_post_gen/blob/7cf49de8f346ef8c1cad319a477b394ce8caeda9/run.sh#L494
`-d` is an alias for `--depsOnly`

From `nimble --help`
> install
> [-d, --depsOnly]   Only install dependencies. Leave out pkgname

Without `-d`, nimble derives a package from the local sources and installs it in `${HOME}/.nimble/pkgs2`. It doesn't make sense for this project to install `nim_con` or `nim` in the local package cache, and it *might* be screwing up the builds. A lot of work went into nimble, but it's got a lot of problems and limitations also.

I added `-d` for the single-threaded implementation in #237, but that PR wasn't merged and I forgot to add it to `run_nim` like I did for `run_nim_con` in #291.

I can make a PR but opened an issue first in case you have a particular reason for not using `-d`.

**Comment by jinyus** [comment]
No particular reason, you can open the PR

**Comment by michaelsbradleyjr** [comment]
Also, if/when `-d` is added for `nim` and `nim_con`, on any machine where the environment isn't from scratch and builds/runs were being done without `-d`, I highly suggest doing the following before the next build/run
```
$ rm -rf "${HOME}"/.nimble/pkgs2/related*
```
