### ISSUE TITLE
C# concurrent solution needlessly uses max

### ISSUE THREAD

**Issue by schveiguy** [jinyus/related_post_gen#336]
In doing the D concurrent SIMD solution, we copied the C# algorithm (very nice!)

We realized the max call isn't necessary. Why?

Basically, the only way you get into the part to check the vector for larger post counts is when the `Vector.LessThanOrEqualAll` call fails. This means at least *one* byte is going to be greater than the minimum count.

But then the Max call just brings up all the counts less than the minimum to the minimum. It doesn't affect the top5 algorithm at all.

Essentially, the code is the equivalent (for a single number) of:

```d
if(val > minVal)
   if(max(val, minVal) != minVal) // might as well be if(true)
```

So you can remove the whole call to `Vector.Max`

ping @zigzag312

**Comment by jinyus** [comment]
Thanks, fixed in# 337

**Comment by zigzag312** [comment]
Good catch. I added `Vector.LessThanOrEqualAll` when I tried to apply optimization from single threaded C# version to vectorized solution which was implemented with the `Max` method. I didn't realize I made `Max` unnecessary in the process. :)
