### ISSUE TITLE
Erroneous highlighting of best 5K score on multicore

### ISSUE THREAD

**Issue by KennethHoff** [jinyus/related_post_gen#352]
Rust is crowned the winner despite being >1ms slower than C# w/ AoT

![Screenshot_20231021_093456_Firefox](https://github.com/jinyus/related_post_gen/assets/17124533/686b5d1e-a1b6-4f79-9083-2f59f7d02ced)

**Comment by jinyus** [comment]
fixed: https://github.com/jinyus/related_post_gen/commit/1bb7efb420983c26f9212bf3ccca9f2789603cf9
