### ISSUE TITLE
Turn on PGO for every language that supports it

### ISSUE THREAD

**Issue by ArtemkaKun** [jinyus/related_post_gen#361]
Since Go and .NET are using PGO by default and I can't see that they are turned off for this benchmark, I think this will be fair to use PGO for every language that supports it

**Comment by jinyus** [comment]
That is up the to the contributors as I don't have experience with all the languages.

**Comment by ArtemkaKun** [comment]
So you are not against PGO?

**Comment by Imperatorn** [comment]
When I get the time I can enable PGO for D just for fun.

**Comment by jinyus** [comment]
> even if not every language supports it

That'd be a deficiency in the language and the results wouldn't be very useful if all other languages are nerfed.

> When I get the time I can enable PGO for D just for fun.

Sound good 👍
