### ISSUE TITLE
threadpool init

### ISSUE THREAD

**Issue by michaelsbradleyjr** [jinyus/related_post_gen#363]
Concurrent implementations use a threadpool or equivalent. For some langs, initialization of that resource is done explicitly.

In the explicit cases, should threadpool init happen after the processing timer starts or is it okay to do it beforehand?

Some impls do it beforehand e.g. `rust_con` and `AppParallel.java`, some do it afterward e.g. `d_con` and `swift_con`.

Cleaning up that resource is automatic in some langs, and for others it's at least a good practice to do so explicitly. In the latter case, is it okay to do it after the processing timer stops?

I raise the issue because I'm working on some speedups for `nim_con` and if I move threadpool init before timer the starts, the performance is a litter better and the numbers are slightly less bouncy. But then I wondered what other concurrent impls here are doing and saw that it varies.

**Comment by cyrusmsk** [comment]
I would expect all processing (including thread creation) to have after the timer. I think Go also did it in that way

**Comment by jinyus** [comment]
I agree with @cyrusmsk
