### ISSUE TITLE
A lot of solutions drops 'title' in results for speedup

### ISSUE THREAD

**Issue by NoobsEnslaver** [jinyus/related_post_gen#369]
Add check for `title` it `related`.

https://github.com/jinyus/related_post_gen/blob/main/go/main.go#L97
https://github.com/jinyus/related_post_gen/blob/main/rust/src/main.rs#L120 
etc.

**Comment by jinyus** [comment]
Most solutions omit title from the top level. I wrote those so it's ok to do this. 

I just checked d,java,c#,f# and they all do this so it's fine.
