### ISSUE TITLE
Would daScript be OK?

### ISSUE THREAD

**Issue by zigzag312** [jinyus/related_post_gen#373]
Language hasn't yet reached v1.0, but it is used in production by the developer.

> Development state
daScript's current version is 0.4, and it's already being used in production projects at Gaijin Entertainment. Until the release of version 1.0, there will be no patches or fixes for older versions. Instead, all updates and fixes will be made available exclusively in the master branch.

https://dascript.org/

Would you accept implementation in this language?

**Comment by jinyus** [comment]
Yes, go for it
