### ISSUE TITLE
Add R implementation

### ISSUE THREAD

**Issue by Tortar** [jinyus/related_post_gen#382]
I'd like to see an R implementation of the benchmark, will try to add it at some point if nobody else does it (I'm not too well versed in it so I wait if somebody else better than me set up it)

**Comment by cyrusmsk** [comment]
I thought about it.
The problem is with hash maps. But will see what can be done.

**Comment by Tortar** [comment]
It's incredible to me that R doesn't have a native implementation of dictionaries/hash maps

**Comment by Imperatorn** [comment]
Someone could modify and test this to see if it works:

```r
library(jsonlite)

TopN <- 5

# Read the JSON file
jsonText <- fromJSON("../posts.json")

# Extract posts
posts <- jsonText

# Create a list to store indices of posts for each tag
tagMap <- vector("list", length = length(unique(unlist(lapply(posts$tags, unique)))))

# Populate tagMap
for (i in seq_along(posts)) {
  for (tag in posts$tags[[i]]) {
    tagMap[[tag]] <- c(tagMap[[tag]], i)
  }
}

# Function to get top related posts
getRelatedPosts <- function(post, posts, tagMap) {
  taggedPostsCount <- numeric(length(posts))
  for (tag in post$tags) {
    for (idx in tagMap[[tag]]) {
      taggedPostsCount[idx] <- taggedPostsCount[idx] + 1
    }
  }
  
  taggedPostsCount[[which(names(taggedPostsCount) == post$_id)]] <- 0
  topIndices <- order(-taggedPostsCount)[1:TopN]
  topRelated <- posts[topIndices]
  
  return(list(_id = post$_id, tags = post$tags, related = topRelated))
}

# Apply the function to each post
relatedPosts <- lapply(posts, getRelatedPosts, posts = posts, tagMap = tagMap)

# Write to JSON
toJSON(relatedPosts, pretty = TRUE, auto_unbox = TRUE) %>% 
  writeLines("../related_posts_r.json")
```

**Comment by cyrusmsk** [comment]
chatGPT is bad at R :)
Also for loops are Stop sings in R world.. so the whole algorithm should be optimised

**Comment by Imperatorn** [comment]
> chatGPT is bad at R :) Also for loops are Stop sings in R world.. so the whole algorithm should be optimised

You can write a version for R

**Comment by cyrusmsk** [comment]
Hey @Tortar
how is your diving into LLVM fluctuations of Julia?

If you will have time - you can also check R implementation. Maybe you will have some suggestions for improving performance
https://github.com/jinyus/related_post_gen/pull/435

**Comment by Tortar** [comment]
Hy @cyrusmsk, oh you noticed my struggle :D 

I think that the problem is with reproducible binaries in Julia, there are some slight differences in the Julia binaries even for the same code which I think can cause this problem. I think it could be since Rust made a lot of work on reproducibility of binaries, see https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AA-reproducibility, and some PRs talked about the relation between variations in binaries and variations in performance. But I didn't get deeper on this since I'm short on time with other tasks.

For what regards the R implementation I will try, but I don't usually use R in my workflow and so I'm not well versed enough to spot perf issues fast, maybe some more experienced R programmer will be interested in trying to improve the performance of it after showing the time of the current solution on the benchmark table :-)
