### ISSUE TITLE
SIMD: hardware targeting

### ISSUE THREAD

**Issue by michaelsbradleyjr** [jinyus/related_post_gen#390]
I'm asking because I've not attempted to work with SIMD previously and I may misunderstand some things.

The rules here include *"No hardware targeting"*.

But  SIMD is allowed for multi-threaded implementations, right? E.g. `d_con` and `csharp_con` take advantage of it.

So as long as after a runtime check for what extensions are available, e.g. SSE2 and/or AVX2, there's a fallback to a non-SIMD algorithm in case no extensions are available, then it's okay?

Some compilers/optimizers may be doing that detection-fallback automatically, e.g. `d_con` and `csharp_con` and their use of vectors *might* involve automatic fallback, I'm not entirely sure.

For `nim_con`, I'm sure I would need to do it manually via [`nimsimd`](https://github.com/guzba/nimsimd) or learn/use a library like [`arraymancer`](https://github.com/mratsim/Arraymancer) that can do it transparently (I think).

**Comment by cyrusmsk** [comment]
Actually I think, that what was used now, more correctly will be call not SIMD, but auto vectorization (but of course it is using SIMD under the hood).
Because explicit SIMD instructions will require specific knowledge of available commands and processor's type.

So as you can see instead of using scary intrinsics like _mm_add_epi64
It is possible to have gain from SIMD with easier and much more readable and maintainable code.

For example you can check this blog post about C++: https://blog.minhazav.dev/guide-compiler-to-auto-vectorise/
And for Nim I think instead of libraries mentioned in your message, you can take a look at this one https://github.com/SciNim/vectorize

**Comment by michaelsbradleyjr** [comment]
> auto vectorization (but of course it is using SIMD under the hood).

Right, that's one of the points I made, perhaps not expressed too well.

`vectorize` is by the same author as `arraymancer`. I'll double-check, but I'm pretty sure the facilities it provides are subsumed by `arraymancer`, which also embeds that same author's `laser` library.

**Comment by cyrusmsk** [comment]
> > auto vectorization (but of course it is using SIMD under the hood).
> 
> Right, that's one of the points I made, perhaps not expressed too well.
> 
> `vectorize` is by the same author as `arraymancer`. I'll double-check, but I'm pretty sure the facilities it provides are subsumed by `arraymancer`, which also embeds that same author's `laser` library.

Maybe you can use them as well. But they are more tensor-libraries (with many backends, including BLAS/LAPACK/GPU). And it could be an overkill to bring them into this problem.

**Comment by michaelsbradleyjr** [comment]
> And it could be an overkill to bring them into this problem.

`vectorize` and standalone `laser` aren't actively maintained and there were important changes re: Nim 2.0 in the last couple of years. `arraymancer` is maintained, though I understand there are some gotchas with Nim 2.0.

I can probably use a 1-tensor (effectively a vector) via `arraymancer` and achieve what's needed with [`>.`](https://github.com/mratsim/Arraymancer/blob/master/src/arraymancer/tensor/operators_comparison.nim#L142-L146) and [`==.`](https://github.com/mratsim/Arraymancer/blob/master/src/arraymancer/tensor/operators_comparison.nim#L111-L115).  I'll see how it goes, and if it performs poorly because of setup-overhead, I'll try do it manually with memory-aligned seq/array and `nimsimd`.

**Comment by jinyus** [comment]
I guess your query was answered. Implementation is up to the contributor and there's no restrictions on mc solutions.

**Comment by michaelsbradleyjr** [comment]
> Implementation is up to the contributor and there's no restrictions on mc solutions.

Answered now, in any case. 😀
