### ISSUE TITLE
SIMD: single-threaded prohibition

### ISSUE THREAD

**Issue by michaelsbradleyjr** [jinyus/related_post_gen#391]
I'm not asking / arguing for a change, just want to understand better.

The rules here include *"No SIMD for single threaded solutions"*.

But SIMD and multi-threading are orthogonal, i.e. you can make use of one but not the other. So is the idea to restrict use of something that would be out-of-reach for many single-threaded dynamic langs (either they don't/can't leverage it automatically and/or don't expose it to the developer), and therefore keep the playing field a bit more level for single-threaded implementations?

**Comment by Moelf** [comment]
I guess if you interpret SIMD generally, multi-threading is a form of SIMD. But in the case of multi-threading, we should also ban `SIMD` (CPU vectorized instruction)

**Comment by jinyus** [comment]
Correct, the restriction was put in place to level the playing field.
