### ISSUE TITLE
LuaJIT results

### ISSUE THREAD

**Issue by AntonYudintsev** [jinyus/related_post_gen#406]
Better have both nojit and jit results (as LuaJit is capable of doing both interpretation and JiT), or at least specify what was used in a table.

**Comment by jinyus** [comment]
Both are in the table: https://github.com/jinyus/related_post_gen#updated-results-from-github-workflow-raw-data

**Comment by AntonYudintsev** [comment]
There is Lua and LuaJIT. But LuaJIT is always run with JIT, without -joff flag, so it is always run with JIT on. 
Besides being fast JIT compiler, luaJIT is one of the fastest _interpeters_ (not to confuse with Lua, which also can be run with and without jit).

**Comment by jinyus** [comment]
#409
