### ISSUE TITLE
LuaJIT results

### ISSUE THREAD

**Issue by AntonYudintsev** [jinyus/related_post_gen#408]
There is Lua and LuaJIT. But LuaJIT in this benchmark always run with JIT, without -joff flag, so it is always run with JIT on.

Besides being fast JIT compiler, luaJIT is one of the fastest interpreters (not to confuse with Lua, which also can be run with and without jit).
At least mark it in results table that LuaJIT is with Jit on

**Comment by jinyus** [comment]
dup #406
