### ISSUE TITLE
Question regarding latest results

### ISSUE THREAD

**Issue by Imperatorn** [jinyus/related_post_gen#427]
There seems to be a drastic regression in the latest results for languages that were previously on top.

Do you know why that might be?

**Comment by jinyus** [comment]
Go and D did suffer perf degradation after updating their compilers: https://github.com/jinyus/related_post_gen/pull/414#issuecomment-1808287956

I downgraded the golang compiler which fixed the issue: https://github.com/jinyus/related_post_gen/pull/421#issue-1989611170

Is there any other language where you noticed regressions?

**Comment by Imperatorn** [comment]
> Go and D did suffer perf degradation after updating their compilers: [#414 (comment)](https://github.com/jinyus/related_post_gen/pull/414#issuecomment-1808287956)
> 
> I downgraded the golang compiler which fixed the issue for go: [#421 (comment)](https://github.com/jinyus/related_post_gen/pull/421#issue-1989611170)
> 
> @cyrusmsk said he'd do the same for D. I will look into it today if he doesn't get a chance to do it.
> 
> Is there any other language where you noticed regressions?

Didn't C# also loose some points? I don't remember, but wasn't it higher up? 🤔

**Comment by cyrusmsk** [comment]
Honestly I'm not sure that the issue in the updated version of compiler. But will see if manual installation of 1.34 LDC will help

**Comment by jinyus** [comment]
@cyrusmsk @Imperatorn Just confirmed https://github.com/jinyus/related_post_gen/pull/429#issuecomment-1811459004. Performance is back to normal with 1.34.0 beta 1.

**Comment by Imperatorn** [comment]
> @cyrusmsk @Imperatorn Just confirmed [#429 (comment)](https://github.com/jinyus/related_post_gen/pull/429#issuecomment-1811459004). Performance is back to normal with 1.34.0 beta 1.

Thanks for investigating!

**Comment by jinyus** [comment]
https://github.com/jinyus/related_post_gen/blob/2d76d834bd758dfd4465952fe9884fdce6ef1805/readme.md?plain=1#L70

I will close this now.
