### ISSUE TITLE
Add PyPy for Python tests

### ISSUE THREAD

**Issue by dbohdan** [jinyus/related_post_gen#486]
PyPy is substantially faster than CPython on [kostya/benchmarks](https://github.com/kostya/benchmarks/). Unfortunately, orjson doesn't support PyPy. The standard library JSON parser should be faster than in CPython.

**Comment by jinyus** [comment]
orjson can be removed as json time is no longer measured. I'll put this on the backburner as I'm busy but you are welcome to submit a PR.
