### ISSUE TITLE
Include at least QuickJS, Deno in JavaScript tests

### ISSUE THREAD

**Issue by guest271314** [jinyus/related_post_gen#63]
Rationale: `node` and `bun` are not the only representatives of JavaScript runtimes.

**Comment by jinyus** [comment]
Added deno. Implemented quickjs but it was very slow on my machine. Will not add it since it's not fast enough to compete. Take a look at the code:
[https://github.com/jinyus/related_post_gen/blob/quickjs/js/quickjs.js](https://github.com/jinyus/related_post_gen/blob/quickjs/js/quickjs.js)

**Comment by guest271314** [comment]
> Will not add it since it's not fast enough to compete. 

That's not the point. The point is empirical data. QuickJS is faster than Node.js, Deno, and Bun as a Native Messaging host.

You are running a single test. When you beging writing different tests you will get different results.

[native_messaging_javascript_runtime_tests](https://gist.github.com/guest271314/fb8969a956a873e495b890a42ac0d731)

```
[{
  "nm_qjs": 0.2468439999997615
}, {
  "nm_bun": 0.2530850000003726
}, {
  "nm_deno": 0.34589599999971704
}, {
  "nm_nodejs": 0.36726300000011924
}]
```

**Comment by jinyus** [comment]
I don't get your point. 
Quickjs might be faster in that I/O heavy test but it's slower in this computational workload. 
If you can improve the code to make it faster, be my guest. It take 1.6s on my machine.

I guess I can add it to the repo but I won't clutter the charts with another js runtime, especially if it's slower.

**Comment by guest271314** [comment]
> I guess I can add it to the repo but I won't clutter the charts with another js runtime, especially if it's slower.

I thought this repository was about empirical data?

It doesn't matter which programming language or runtime is slower or faster. Using your own logic should you remove Bun? And leave only Node.js? How will QuickJS maintainer and the downstream txiki.js know how "slow" that runtime is cf. other JavaScript runtimes when the data is intentionally excluded from the graph?

You are only running one kind of test and extrapolating a general speed from that single test. That is hardly comprehensive. I suspect you will add other tests, in which case you have prematurely excluded QuickJS, and therefore won;t know if QuickJS is "faster" in those instances.

It's your repository. Do as you will. I will tell you this, I didn;t have an expectation about which JavaScript runtime was faster when running Native Messaging tests. I let the data speak for itself.

**Comment by guest271314** [comment]
I'll point this out as well. While QuickJS might be slower than Deno, Node, Bun, et al. in some cases, QuickJS is the choice for embedding in WebAssembly/WASI applications because after `strip` the `qjs` executable is less than 1 MB. In general, developers are not trying to compile `node`, `deno` or `bun` to WASM for embedding into WASI as a JavaScript runtime at 90-100+ MB. So, there is a trade-off.

**Comment by guest271314** [comment]
@jinyus Nit: Technically Node.js, Deno, Bun are not _Languages_. They are JavaScript programming language runtimes. I didn't file another issue, though I cn.
