### ISSUE TITLE
Does verify.py work as intended?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [jinyus/related_post_gen#86]
I'm working this evening on a revision to the Nim implementation. I noticed that when running `./run.sh rust` or `./run.sh nim` or whatever, if I then manually edit the output in `related_posts_rust.json` it doesn't cause verification to fail. For example, I tried removing some entries in the top-level array, and I also tried replacing the contents of the file with `[]` or `{}` — in any of those cases, `verify.py` does not exit with error.

**Comment by jinyus** [comment]
Thanks for reporting, I will fix that. It's mainly to check that the top5 related posts are correct. It doesn't verify that there are indeed 5000 posts.

**Comment by jinyus** [comment]
Fixed

**Comment by michaelsbradleyjr** [comment]
I may be misunderstanding one or more things...
I took the output of
```
./run.sh rust && cat related_posts_rust.json | jq 'sort_by(._id)' > A.json
```
and the output of
```
./run.sh py && cat related_posts_python.json | jq 'sort_by(._id)' > B.json
```

I was *not* surprised to see that they are not a match with that shallow sort, using
```
jd -set A.json B.json
```
cf. https://github.com/josephburnett/jd

Because I understand that depending on the implementation and the lang/runtime, the resulting array order can legitimately differ.

However, before I spent more time with `jq` and `jd` to get a comparison that's not sensitive to array order at all levels, I eyeballed `A.json` and `B.json` side-by-side, and the first object with `"_id": "00n3qp9q"` in `A.json` has an object with `"_id": "7rm5eqic"` in its `related` array, while the first object with `"_id": "00n3qp9q"` in `B.json` does not have that object but instead one with `"_id": "0ce1xh4z`. That's just one example where the objects in the top-level arrays don't match, even if we allow for ordering in arrays to differ.

Again, I may misunderstand something/s very badly, but it seems to me that in order to have meaningful comparisons in terms of performance, there needs to be certainty that the various implementations generate equivalent output.

Otherwise, how can one know if an implementation is faster than another because its lang/runtime is fast or instead because it was written in a way that doesn't do the steps correctly and effectively "takes a shortcut" because of incorrectness? I wonder even while working on the revised Nim code if I'm not making mistakes if I don't have a baseline for comparison.

**Comment by jinyus** [comment]
This is because the posts can have the same amount of shared tags. so anyone of them can end up in the related list.

eg: Let's say we have

post1:

related:
post5: shares 5 tags with posts1
post5: shares 5 tags with posts1
post5: shares 5 tags with posts1

**Comment by jinyus** [comment]
This is because many posts can have the same amount of shared tags. so anyone of them can end up in the related list. This is why I tally up the shared tags to make sure they are the same as the correct file.

eg: Let's say we have post_1:


post_15: shares 5 tags with post_1
post_50: shares 4 tags with post_1
post_61: shares 4 tags with post_1
post_75: shares 3 tags with post_1
post_77: shares 2 tags with post_1
post_85: shares 2 tags with post_1
post_93: shares 2 tags with post_1

if we select the top 5 posts based on the amount of shared tags. The last post in the related list could be either post_77, post_85 or post_93 since they have the same ranking.

**Comment by michaelsbradleyjr** [comment]
That makes sense, certainly.

It's your project, so definitely proceed in whatever way makes sense to you. My perspective: I would value having the same deterministic output as the target for each and every language, because comparing the runtime lengths of programs `X` and `Y` would mean comparing how long they each took to produce the exact same output, or at least equivalent output if the verifier program/tool (e.g. `jd`) can account for differences in key/index ordering.

**Comment by jinyus** [comment]
Remember that the algorithm discards post ids, so from that perspective, they would all return 5,4,4,3,2 for the example above. So it's deterministic in that regard.

**Comment by michaelsbradleyjr** [comment]
Could the rules be adapted so that the expected output is the same as / equivalent to the contents of what's in `correct_related.json`?

Checking that the output of the python, rust, nim, etc. implementation is correct would then be as simple as e.g.
```
$ jd correct_related.json related_posts_nim.json
```
(takes way less than a second on my laptop to compare two copies of `correct_related.json`)

Even if the key ordering is different, so long as it's all the same keys and values, the command exits with success (`0`), otherwise it would exit with error (`1`).

**Comment by jinyus** [comment]
No, I want it to output useful data and every other implementation would need to be modified. T

**Comment by michaelsbradleyjr** [comment]
Fair enough. I'll submit a revised Nim PR for you to consider, without any of the changes/ideas discussed in this issue. Best of luck with the project.
